version: "3.2"

services:
  zookeeper:
    image: jplock/zookeeper
    networks:       
      - sw_network
    ports:
      - 2181:2181

  wallet:
    image: hrzn/wallet:latest
    depends_on:
      - zookeeper
    networks:       
      - sw_network
    deploy:
      replicas: 3
        
  wallet_rest:
    image: hrzn/wallet_rest:latest
    depends_on:
      - zookeeper
      - wallet
    ports:
      - 9090:9090
    networks:       
      - sw_network
    deploy:
      replicas: 1

networks:
  sw_network:
    external:
      name: akka_cluster
