version: "3.4"

services:

  wallet:
    image: eshepelyuk/wallet:latest
    networks:       
      - sw_network
    deploy:
      replicas: 2
        
  wallet_rest:
    image: eshepelyuk/wallet_rest:latest
    ports:
      - 9090:9090
    networks:       
      - sw_network
    deploy:
      replicas: 1
      
networks:
  sw_network:
    external:
      name: akka_cluster
